# Generated by Django 3.1.7 on 2021-04-16 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('budgets', '0004_auto_20210416_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='budgets.budget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
