version: "3.3"
   
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=familybudget
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      
  djangorest:
    build: .
    command: bash -c 'wait-for-it postgres:5432 -s --timeout=15 -- ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./FamilyBudget:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
